// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Name      string      `json:"name"`
	Weekdays  []int16     `json:"weekdays"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

type Event struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Goal struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Title          string             `json:"title"`
	WeeklyTarget   int16              `json:"weekly_target"`
	SessionMinutes int16              `json:"session_minutes"`
	GithubRepo     *string            `json:"github_repo"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
}

type Integration struct {
	UserID               uuid.UUID `json:"user_id"`
	GithubLogin          *string   `json:"github_login"`
	GithubTokenEncrypted []byte    `json:"github_token_encrypted"`
}

type Quest struct {
	ID           uuid.UUID          `json:"id"`
	GoalID       uuid.UUID          `json:"goal_id"`
	UserID       uuid.UUID          `json:"user_id"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	Status       string             `json:"status"`
	DoneAt       pgtype.Timestamptz `json:"done_at"`
}

type SkipDay struct {
	UserID  uuid.UUID   `json:"user_id"`
	SkipDay pgtype.Date `json:"skip_day"`
}

type Streak struct {
	GoalID    uuid.UUID          `json:"goal_id"`
	Current   int16              `json:"current"`
	Best      int16              `json:"best"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Timezone     string             `json:"timezone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
