// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSkipDay = `-- name: AddSkipDay :exec
INSERT INTO skip_days (user_id, skip_day)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSkipDayParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	SkipDay pgtype.Date `json:"skip_day"`
}

func (q *Queries) AddSkipDay(ctx context.Context, arg AddSkipDayParams) error {
	_, err := q.db.Exec(ctx, addSkipDay, arg.UserID, arg.SkipDay)
	return err
}

const archiveGoal = `-- name: ArchiveGoal :exec
UPDATE goals SET archived_at = now() WHERE id = $1 AND user_id = $2
`

type ArchiveGoalParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ArchiveGoal(ctx context.Context, arg ArchiveGoalParams) error {
	_, err := q.db.Exec(ctx, archiveGoal, arg.ID, arg.UserID)
	return err
}

const clearGitHubIntegration = `-- name: ClearGitHubIntegration :exec
UPDATE integrations SET github_login = NULL, github_token_encrypted = NULL WHERE user_id = $1
`

func (q *Queries) ClearGitHubIntegration(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearGitHubIntegration, userID)
	return err
}

const completeFirstPendingQuestByRepo = `-- name: CompleteFirstPendingQuestByRepo :one
UPDATE quests
SET status = 'done', done_at = now()
WHERE id = (
    SELECT q.id FROM quests q
    JOIN goals g ON g.id = q.goal_id
    WHERE q.user_id = $1
      AND q.status = 'pending'
      AND q.scheduled_for >= $2
      AND q.scheduled_for < $3
      AND g.github_repo = $4
    ORDER BY q.scheduled_for
    LIMIT 1
)
RETURNING id, goal_id, user_id, scheduled_for, status, done_at
`

type CompleteFirstPendingQuestByRepoParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	ScheduledFor   pgtype.Timestamptz `json:"scheduled_for"`
	ScheduledFor_2 pgtype.Timestamptz `json:"scheduled_for_2"`
	GithubRepo     *string            `json:"github_repo"`
}

func (q *Queries) CompleteFirstPendingQuestByRepo(ctx context.Context, arg CompleteFirstPendingQuestByRepoParams) (Quest, error) {
	row := q.db.QueryRow(ctx, completeFirstPendingQuestByRepo,
		arg.UserID,
		arg.ScheduledFor,
		arg.ScheduledFor_2,
		arg.GithubRepo,
	)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.ScheduledFor,
		&i.Status,
		&i.DoneAt,
	)
	return i, err
}

const countDoneQuestsForGoalBetween = `-- name: CountDoneQuestsForGoalBetween :one
SELECT COUNT(*) FROM quests
WHERE goal_id = $1 AND status = 'done'
  AND scheduled_for >= $2 AND scheduled_for < $3
`

type CountDoneQuestsForGoalBetweenParams struct {
	GoalID         uuid.UUID          `json:"goal_id"`
	ScheduledFor   pgtype.Timestamptz `json:"scheduled_for"`
	ScheduledFor_2 pgtype.Timestamptz `json:"scheduled_for_2"`
}

func (q *Queries) CountDoneQuestsForGoalBetween(ctx context.Context, arg CountDoneQuestsForGoalBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDoneQuestsForGoalBetween, arg.GoalID, arg.ScheduledFor, arg.ScheduledFor_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSkipDaysInWeek = `-- name: CountSkipDaysInWeek :one
SELECT COUNT(*) FROM skip_days
WHERE user_id = $1 AND skip_day >= $2 AND skip_day < $3
`

type CountSkipDaysInWeekParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	SkipDay   pgtype.Date `json:"skip_day"`
	SkipDay_2 pgtype.Date `json:"skip_day_2"`
}

func (q *Queries) CountSkipDaysInWeek(ctx context.Context, arg CountSkipDaysInWeekParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSkipDaysInWeek, arg.UserID, arg.SkipDay, arg.SkipDay_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlock = `-- name: CreateBlock :one
INSERT INTO blocks (user_id, name, weekdays, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, weekdays, start_time, end_time
`

type CreateBlockParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Name      string      `json:"name"`
	Weekdays  []int16     `json:"weekdays"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error) {
	row := q.db.QueryRow(ctx, createBlock,
		arg.UserID,
		arg.Name,
		arg.Weekdays,
		arg.StartTime,
		arg.EndTime,
	)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Weekdays,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (user_id, title, starts_at, ends_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, starts_at, ends_at, created_at
`

type CreateEventParams struct {
	UserID   uuid.UUID          `json:"user_id"`
	Title    string             `json:"title"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.UserID,
		arg.Title,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (user_id, title, weekly_target, session_minutes, github_repo)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, weekly_target, session_minutes, github_repo, created_at, archived_at
`

type CreateGoalParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Title          string    `json:"title"`
	WeeklyTarget   int16     `json:"weekly_target"`
	SessionMinutes int16     `json:"session_minutes"`
	GithubRepo     *string   `json:"github_repo"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.Title,
		arg.WeeklyTarget,
		arg.SessionMinutes,
		arg.GithubRepo,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.WeeklyTarget,
		&i.SessionMinutes,
		&i.GithubRepo,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createQuest = `-- name: CreateQuest :one
INSERT INTO quests (goal_id, user_id, scheduled_for)
VALUES ($1, $2, $3)
RETURNING id, goal_id, user_id, scheduled_for, status, done_at
`

type CreateQuestParams struct {
	GoalID       uuid.UUID          `json:"goal_id"`
	UserID       uuid.UUID          `json:"user_id"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
}

func (q *Queries) CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error) {
	row := q.db.QueryRow(ctx, createQuest, arg.GoalID, arg.UserID, arg.ScheduledFor)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.ScheduledFor,
		&i.Status,
		&i.DoneAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, timezone)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, timezone, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Timezone     string `json:"timezone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Timezone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks WHERE id = $1 AND user_id = $2
`

type DeleteBlockParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.ID, arg.UserID)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1 AND user_id = $2
`

type DeleteEventParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.Exec(ctx, deleteEvent, arg.ID, arg.UserID)
	return err
}

const deletePendingQuestByID = `-- name: DeletePendingQuestByID :exec
DELETE FROM quests WHERE id = $1 AND status = 'pending'
`

func (q *Queries) DeletePendingQuestByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingQuestByID, id)
	return err
}

const deletePendingQuestsByGoal = `-- name: DeletePendingQuestsByGoal :exec
DELETE FROM quests WHERE goal_id = $1 AND status = 'pending'
`

func (q *Queries) DeletePendingQuestsByGoal(ctx context.Context, goalID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingQuestsByGoal, goalID)
	return err
}

const findGoalByRepo = `-- name: FindGoalByRepo :one
SELECT id, user_id, title, weekly_target, session_minutes, github_repo, created_at, archived_at FROM goals
WHERE user_id = $1 AND github_repo = $2 AND archived_at IS NULL
LIMIT 1
`

type FindGoalByRepoParams struct {
	UserID     uuid.UUID `json:"user_id"`
	GithubRepo *string   `json:"github_repo"`
}

func (q *Queries) FindGoalByRepo(ctx context.Context, arg FindGoalByRepoParams) (Goal, error) {
	row := q.db.QueryRow(ctx, findGoalByRepo, arg.UserID, arg.GithubRepo)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.WeeklyTarget,
		&i.SessionMinutes,
		&i.GithubRepo,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getStreak = `-- name: GetStreak :one
SELECT goal_id, current, best, updated_at FROM streaks WHERE goal_id = $1
`

func (q *Queries) GetStreak(ctx context.Context, goalID uuid.UUID) (Streak, error) {
	row := q.db.QueryRow(ctx, getStreak, goalID)
	var i Streak
	err := row.Scan(
		&i.GoalID,
		&i.Current,
		&i.Best,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, timezone, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, timezone, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIDByGitHubLogin = `-- name: GetUserIDByGitHubLogin :one
SELECT user_id FROM integrations WHERE github_login = $1
`

func (q *Queries) GetUserIDByGitHubLogin(ctx context.Context, githubLogin *string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByGitHubLogin, githubLogin)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const listBlocks = `-- name: ListBlocks :many
SELECT id, user_id, name, weekdays, start_time, end_time FROM blocks WHERE user_id = $1 ORDER BY start_time
`

func (q *Queries) ListBlocks(ctx context.Context, userID uuid.UUID) ([]Block, error) {
	rows, err := q.db.Query(ctx, listBlocks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Weekdays,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsBetween = `-- name: ListEventsBetween :many
SELECT id, user_id, title, starts_at, ends_at, created_at FROM events
WHERE user_id = $1
  AND starts_at < $2
  AND ends_at > $3
ORDER BY starts_at
`

type ListEventsBetweenParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	RangeEnd   pgtype.Timestamptz `json:"range_end"`
	RangeStart pgtype.Timestamptz `json:"range_start"`
}

func (q *Queries) ListEventsBetween(ctx context.Context, arg ListEventsBetweenParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsBetween, arg.UserID, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, user_id, title, weekly_target, session_minutes, github_repo, created_at, archived_at FROM goals
WHERE user_id = $1 AND archived_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListGoals(ctx context.Context, userID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.WeeklyTarget,
			&i.SessionMinutes,
			&i.GithubRepo,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsForUser = `-- name: ListGoalsForUser :many
SELECT id, user_id, title, weekly_target, session_minutes, github_repo, created_at, archived_at FROM goals WHERE user_id = $1 AND archived_at IS NULL
`

func (q *Queries) ListGoalsForUser(ctx context.Context, userID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoalsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.WeeklyTarget,
			&i.SessionMinutes,
			&i.GithubRepo,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingQuestsForGoalOnDate = `-- name: ListPendingQuestsForGoalOnDate :many
SELECT id, goal_id, user_id, scheduled_for, status, done_at FROM quests
WHERE goal_id = $1
  AND status = 'pending'
  AND scheduled_for >= $2
  AND scheduled_for < $3
ORDER BY scheduled_for
`

type ListPendingQuestsForGoalOnDateParams struct {
	GoalID         uuid.UUID          `json:"goal_id"`
	ScheduledFor   pgtype.Timestamptz `json:"scheduled_for"`
	ScheduledFor_2 pgtype.Timestamptz `json:"scheduled_for_2"`
}

func (q *Queries) ListPendingQuestsForGoalOnDate(ctx context.Context, arg ListPendingQuestsForGoalOnDateParams) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listPendingQuestsForGoalOnDate, arg.GoalID, arg.ScheduledFor, arg.ScheduledFor_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quest
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.ScheduledFor,
			&i.Status,
			&i.DoneAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestsBetween = `-- name: ListQuestsBetween :many
SELECT id, goal_id, user_id, scheduled_for, status, done_at FROM quests
WHERE user_id = $1 AND scheduled_for >= $2 AND scheduled_for < $3
ORDER BY scheduled_for
`

type ListQuestsBetweenParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	ScheduledFor   pgtype.Timestamptz `json:"scheduled_for"`
	ScheduledFor_2 pgtype.Timestamptz `json:"scheduled_for_2"`
}

func (q *Queries) ListQuestsBetween(ctx context.Context, arg ListQuestsBetweenParams) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listQuestsBetween, arg.UserID, arg.ScheduledFor, arg.ScheduledFor_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quest
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.ScheduledFor,
			&i.Status,
			&i.DoneAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsWithActiveGoals = `-- name: ListUserIDsWithActiveGoals :many
SELECT DISTINCT user_id FROM goals WHERE archived_at IS NULL
`

func (q *Queries) ListUserIDsWithActiveGoals(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserIDsWithActiveGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markQuestDone = `-- name: MarkQuestDone :one
UPDATE quests
SET status = 'done', done_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'pending'
RETURNING id, goal_id, user_id, scheduled_for, status, done_at
`

type MarkQuestDoneParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkQuestDone(ctx context.Context, arg MarkQuestDoneParams) (Quest, error) {
	row := q.db.QueryRow(ctx, markQuestDone, arg.ID, arg.UserID)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.ScheduledFor,
		&i.Status,
		&i.DoneAt,
	)
	return i, err
}

const setGitHubIntegration = `-- name: SetGitHubIntegration :exec
INSERT INTO integrations (user_id, github_login, github_token_encrypted)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET github_login = EXCLUDED.github_login,
    github_token_encrypted = EXCLUDED.github_token_encrypted
`

type SetGitHubIntegrationParams struct {
	UserID               uuid.UUID `json:"user_id"`
	GithubLogin          *string   `json:"github_login"`
	GithubTokenEncrypted []byte    `json:"github_token_encrypted"`
}

func (q *Queries) SetGitHubIntegration(ctx context.Context, arg SetGitHubIntegrationParams) error {
	_, err := q.db.Exec(ctx, setGitHubIntegration, arg.UserID, arg.GithubLogin, arg.GithubTokenEncrypted)
	return err
}

const skipPendingQuestsOnDate = `-- name: SkipPendingQuestsOnDate :exec
UPDATE quests
SET status = 'skipped'
WHERE user_id = $1
  AND status = 'pending'
  AND scheduled_for >= $2
  AND scheduled_for < $3
`

type SkipPendingQuestsOnDateParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	ScheduledFor   pgtype.Timestamptz `json:"scheduled_for"`
	ScheduledFor_2 pgtype.Timestamptz `json:"scheduled_for_2"`
}

func (q *Queries) SkipPendingQuestsOnDate(ctx context.Context, arg SkipPendingQuestsOnDateParams) error {
	_, err := q.db.Exec(ctx, skipPendingQuestsOnDate, arg.UserID, arg.ScheduledFor, arg.ScheduledFor_2)
	return err
}

const undoQuest = `-- name: UndoQuest :one
UPDATE quests
SET status = 'pending', done_at = NULL
WHERE id = $1 AND user_id = $2 AND status IN ('done', 'skipped')
RETURNING id, goal_id, user_id, scheduled_for, status, done_at
`

type UndoQuestParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UndoQuest(ctx context.Context, arg UndoQuestParams) (Quest, error) {
	row := q.db.QueryRow(ctx, undoQuest, arg.ID, arg.UserID)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.ScheduledFor,
		&i.Status,
		&i.DoneAt,
	)
	return i, err
}

const updateBlock = `-- name: UpdateBlock :one
UPDATE blocks
SET name = $2, weekdays = $3, start_time = $4, end_time = $5
WHERE id = $1 AND user_id = $6
RETURNING id, user_id, name, weekdays, start_time, end_time
`

type UpdateBlockParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Weekdays  []int16     `json:"weekdays"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateBlock(ctx context.Context, arg UpdateBlockParams) (Block, error) {
	row := q.db.QueryRow(ctx, updateBlock,
		arg.ID,
		arg.Name,
		arg.Weekdays,
		arg.StartTime,
		arg.EndTime,
		arg.UserID,
	)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Weekdays,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET title = $2, weekly_target = $3, session_minutes = $4, github_repo = $5
WHERE id = $1 AND user_id = $6 AND archived_at IS NULL
RETURNING id, user_id, title, weekly_target, session_minutes, github_repo, created_at, archived_at
`

type UpdateGoalParams struct {
	ID             uuid.UUID `json:"id"`
	Title          string    `json:"title"`
	WeeklyTarget   int16     `json:"weekly_target"`
	SessionMinutes int16     `json:"session_minutes"`
	GithubRepo     *string   `json:"github_repo"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.Title,
		arg.WeeklyTarget,
		arg.SessionMinutes,
		arg.GithubRepo,
		arg.UserID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.WeeklyTarget,
		&i.SessionMinutes,
		&i.GithubRepo,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const upsertStreak = `-- name: UpsertStreak :one
INSERT INTO streaks (goal_id, current, best, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (goal_id) DO UPDATE
SET current = EXCLUDED.current,
    best = GREATEST(streaks.best, EXCLUDED.best),
    updated_at = now()
RETURNING goal_id, current, best, updated_at
`

type UpsertStreakParams struct {
	GoalID  uuid.UUID `json:"goal_id"`
	Current int16     `json:"current"`
	Best    int16     `json:"best"`
}

func (q *Queries) UpsertStreak(ctx context.Context, arg UpsertStreakParams) (Streak, error) {
	row := q.db.QueryRow(ctx, upsertStreak, arg.GoalID, arg.Current, arg.Best)
	var i Streak
	err := row.Scan(
		&i.GoalID,
		&i.Current,
		&i.Best,
		&i.UpdatedAt,
	)
	return i, err
}
