DROP TABLE IF EXISTS skip_days;
DROP TABLE IF EXISTS integrations;
DROP TABLE IF EXISTS streaks;
DROP TABLE IF EXISTS quests;
DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS blocks;
DROP TABLE IF EXISTS users;
